from typing import Protocol

from oompa_types.condition.condition import Condition
from oompa_types.effect.effect import Effect


class SupportsOperators(Protocol):
    def equals(self, desired) -> Condition: ...
    def ne(self, desired) -> Condition: ...

    def not_equals(self, desired) -> Condition: ...

    def lt(self, desired) -> Condition:
        return self.less_than(desired)

    def less_than(self, desired) -> Condition: ...

    def lte(self, desired) -> Condition:
        return self.less_than_equals(desired)

    def less_than_equals(self, desired) -> Condition: ...

    def gt(self, desired) -> Condition: ...

    def greater_than(self, desired) -> Condition: ...

    def gte(self, desired) -> Condition:
        return self.greater_than_equals(desired)

    def greater_than_equals(self, desired) -> Condition: ...

    def contains(self, desired) -> Condition: ...

    def not_contains(self, desired) -> Condition:
        return self.not_contains(desired)

    def fewer_than(self, desired) -> Condition: ...

    def fewer_than_equals(self, desired) -> Condition: ...

    def more_than(self, desired) -> Condition: ...

    def more_than_equals(self, desired) -> Condition: ...

    def assigned(self, desired) -> Effect: ...

    def increased_by(self, desired) -> Effect: ...

    def decreased_by(self, desired) -> Effect: ...

    def reduced_by(self, desired) -> Effect: ...

    def inserts(self, desired) -> Effect: ...

    def removes(self, desired) -> Effect: ...

    def appends(self, desired) -> Effect: ...

    def pushes(self, desired) -> Effect: ...

    def pops(self, desired) -> Effect: ...
